### ISSUE TITLE
I can acces the database which give the data of all customer in database

### ISSUE THREAD

**Issue by 21Gxme** [J-Jullaphong/JongMaiHUB#74]
<img width="1470" alt="image" src="https://github.com/J-Jullaphong/JongMaiHUB/assets/113856957/aa64eab1-645c-485e-9667-f6555d7fc8ea">

[This is the link that I get](https://bjjva2umlr-jongmaihub-backend.onrender.com/api/customer/)

**Comment by J-Jullaphong** [comment]
Fixed it. Thank you for pointing this out.
