### ISSUE TITLE
Can access api endpoints without authorization

### ISSUE THREAD

**Issue by Sosokker** [J-Jullaphong/JongMaiHUB#75]
Can access many API endpoints without authorization such as [Customer Info](https://bjjva2umlr-jongmaihub-backend.onrender.com/api/customer/) and etc.

**Comment by Nuafah** [comment]
Since this issue is the same as [this one](https://github.com/J-Jullaphong/JongMaiHUB/issues/75) we will close this issue and start working on the [issue#75](https://github.com/J-Jullaphong/JongMaiHUB/issues/75).
