### ISSUE TITLE
Customer profile is shown after logout

### ISSUE THREAD

**Issue by fatalaijon** [J-Jullaphong/JongMaiHUB#77]
If a customer views the "My Profile" page and then clicks "Logout",
his profile is still shown on the screen even after he has logged out.

1. Click "My Profile".
2. Make some changes and save them (this step maybe optional).
3. Click Logout under the user icon.
4. There is now a "Login" button, but customer profile is still visible.

this is repeatable.  See attached screenshot.
![jongmai-profile-after-logout](https://github.com/J-Jullaphong/JongMaiHUB/assets/18551033/c001e632-322f-49c4-8691-b20d3c53accc)

**Comment by Nuafah** [comment]
We fixed it. thanks for your observation.
